language: node_js
node_js:
 - "node"
sudo: false
cache:
  directories:
    - node_modules
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
env:
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz 
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.19.1-linux64 -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
before_script:
  - node bin/wwww > /dev/null 2>&1 &