language: node_js
node_js:
 - "node"
addons:
  sauce_connect: true
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
 - node bin/wwww > /dev/null 2>&1 &
script:
 - xvfb-run wct --skip-plugin sauce