language: node_js
node_js:
 - "node"
sudo: false
cache:
  directories:
    - node_modules
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
env:
before_install:
before_script:
  - node bin/wwww > /dev/null 2>&1 &