language: node_js
node_js:
 - "node"
services:
 - postgresql
addons:
  sauce_connect: true
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
 - npm start