language: node_js
node_js:
 - "node"

# Container-based fast boot time environment in which sudo commands are not available
# https://docs.travis-ci.com/user/reference/overview/
sudo: false

cache:
  directories:
    - node_modules
services:
 - postgresql
addons:
  firefox: latest
#  Remove saucelabs until Open Sauce Account is confirmed
#  sauce_connect: true
env:
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz 
  - mkdir geckodriver
  - tar -xzf geckodriver*.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
before_script:
  - psql -c "CREATE DATABASE myteam;" -U postgres
  - psql -U postgres -d myteam -a -f ./scripts/example.sql
  - npm start &