language: node_js
node_js:
 - "node"
sudo: false
cache:
  directories:
    - node_modules
addons:
  firefox: "55.0"
env:
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz 
  - mkdir geckodriver
  - tar -xzf geckodriver*.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start || true
  - firefox --version
  - geckodriver --version
before_script:
  - npm start &