language: node_js
node_js:
 - "node"
services:
  - postgresql
 addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
 - node bin/wwww > /dev/null 2>&1 &